version: "3.1"

services:
  nav-etcd-server:
    image: bitnami/etcd:3.6.3
    container_name: nav-etcd-3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:3379
      - ETCD_ROOT_PASSWORD=changeMe
      - ETCD_LOG_LEVEL=warn
    volumes:
      - ./etcd/conf.yml:/opt/bitnami/Etcd/conf/etcd.conf.yml
    ports:
      - "3379:2379"
      - "3380:2380"

  nav-mysql-server:
    image: "mysql:8.0.23"
    container_name: nav-mysql-8
    command: >
      mysqld --lower-case-table-names=1 --sql-mode="" --default-time-zone="+08:00" --innodb_buffer_pool_size=1073741824 --max_allowed_packet=67108864	--bulk_insert_buffer_size=536870912 --local_infile="on" --binlog_expire_logs_seconds=604800 --skip-name-resolve
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nav_server
    ports:
      - "3308:3306"
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql:delegated
      - ./mysql/conf:/etc/mysql/conf.d:delegated
      - ./mysql/logs:/var/log/mysql:delegated

  nav-redis-standalone:
    image: redis:alpine
    container_name: nav-redis-standalone
    ports:
      - "6399:6379"
    command: redis-server --requirepass fake --save 20 1 --loglevel warning
    volumes:
      - ./redis/data:/data
      - ./redis/config:/usr/local/etc/redis